CREATE TABLE Cibo (
id INT(11) UNSIGNED  NOT NULL AUTO_INCREMENT,
nome VARCHAR(20) NOT NULL,
prezzo DOUBLE NOT NULL,
descrizione VARCHAR(50) NOT NULL,

PRIMARY KEY (id)
);

CREATE TABLE Sede_Universitaria (
id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(20) NOT NULL,
indirizzo VARCHAR(20) NOT NULL,
cap VARCHAR(5) NOT NULL,

 PRIMARY KEY (id)
);

CREATE TABLE Utente (
id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
nome VARCHAR(30) NOT NULL,
cognome VARCHAR(30) NOT NULL,
email VARCHAR(50) NOT NULL,
numero_cellulare VARCHAR(10) NOT NULL,
citta VARCHAR(30) NOT NULL,
cap VARCHAR(5) NOT NULL,
indirizzo VARCHAR(40) NOT NULL,
email_istituzionale VARCHAR(50),
id_sede INT(11) UNSIGNED NOT NULL,

PRIMARY KEY (id),
FOREIGN KEY (id_sede) REFERENCES Sede_Universitaria(id)
);

CREATE TABLE Ordine (
id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
id_cibo INT(11) UNSIGNED NOT NULL,
quantita_cibo INT(5) NOT NULL,
id_utente INT(11) UNSIGNED NOT NULL,

PRIMARY KEY (id),
FOREIGN KEY (id_utente) REFERENCES Utente (id),
FOREIGN KEY (id_cibo) REFERENCES Cibo(id)
);